version: 1.0.{build}

environment:
  global:
    APPVEYOR_OS_NAME: windows
    CHERE_INVOKING: 1
    MSYS2_PATH: c:\msys64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PYTHON: C:\Python36-x64
    #PYTHON_VERSION: "3.6.3"
    #PYTHON_ARCH: "64"
   # PIP: "C:\\Python36-x64\\Scripts\\pip"
  matrix:
  #MSYS2 Building
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  MSYSTEM: MINGW32
    #  WORDSIZE: x86
    #  COMPILER: gcc
    #  BUILDTYPE: msys2
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  WORDSIZE: x64
    #  MSYSTEM: MINGW64
    #  COMPILER: gcc
    #  BUILDTYPE: msys2
  #VisualStudio Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      WORDSIZE: x86
      COMPILER : msvc2017
      BUILDTYPE: msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      WORDSIZE: x64
      COMPILER : msvc2017
      BUILDTYPE: msvc

configuration: Debug
shallow_clone: true
clone_depth: 10

cache:
- '%MSYS2_PATH%\var\cache\pacman'

init:
# Upgrade the MSYS2 system and all install packages
- '%MSYS2_PATH%\usr\bin\pacman --noconfirm -Syu'

install:
# Install required packages for MSYS2 system
- '%MSYS2_PATH%\usr\bin\bash -lc "scripts/ci/${BUILDTYPE}/install.sh"'
- cmd: choco install ninja
- cmd: choco install cmake
- cmd: set PATH=C:\ProgramData\chocolatey\lib\ninja\tools;%PATH%
- cmd: set PATH=%PATH%;C:\Python36-x64\Scripts
- cmd: C:\Python36-x64\Scripts\pip.exe install conan
- cmd: conan user # Create the conan data directory
- cmd: conan --version

before_build:
# Generate Cmake scripts
#- '%MSYS2_PATH%\usr\bin\bash -lc "scripts/ci/msys2/generate.sh"'

build_script:
# Build everything
- if "%BUILDTYPE%"=="msys2" (%MSYS2_PATH%\usr\bin\bash -lc "./mgr.sh build ${COMPILER} ${WORDSIZE}")
- echo "test"
- if "%BUILDTYPE%"=="msvc"  (
    mkdir build &&
    pushd build &&
    conan install .. &&
    where ninja &&
    where cmake &&
    where nmake &&
    set &&
    cmake .. -G "Ninja" &&
    popd
  )

test_script:
  - '%MSYS2_PATH%\usr\bin\bash -lc "./mgr.sh tests ${COMPILER} ${WORDSIZE}"'

